### ISSUE TITLE
Get Twitter feeds from Speakers and organizers

### ISSUE THREAD

**Issue by kathgironpe** [radamanthus/railsjam#8]
There's some limitation to using the twitter search api. To be able to get feeds earlier than this date, there's a need to check RailsJam-related tweets of speakers and  like @gregmoreno and @DevConPH

**Comment by radamanthus** [comment]
If you know the tweeter user ID of the people you want to harvest tweets from, use the Stream API instead of the Search API.

**Comment by kathgironpe** [comment]
Yep. The code is actually ready. I'm just testing. And have yet to design the page.
